# Generated by Django 5.2.5 on 2025-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='email_contato',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
